### ISSUE TITLE
Zeit API does not handle teamId properly

### ISSUE THREAD

**Issue by michaellopez** [sergiodxa/now-storage#11]
This is a crosspost from #9 

As [mentioned there](https://github.com/sergiodxa/now-storage/pull/9#issuecomment-428241300) I'm opening an issue detailing a bug in the Zeit API for handling team scoped requests.

I send a proper Authorization Bearer token for both of these requests.

```
Fails:
GET https://api.zeit.co/v2/now/deployments?teamId=<my team slug>

Succeeds:
GET https://api.zeit.co/v2/now/deployments?teamId=<my team ID>
```

where `<my team ID>` is the ID I get from `GET https://api.zeit.co/teams?slug=<my team slug>`. It looks like `team_<some hash>`.

Let me know if you need anything else @sergiodxa

**Comment by sergiodxa** [comment]
This is fixed on #12
